version: '3'
services:

  traefik:
    image: "traefik:v2.6.6"
    container_name: "traefik-network"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --log.level=DEBUG
      - --certificatesresolvers.letsencrypt.acme.email=felipeng.eletrica@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  apache:
    image: 'bitnami/apache:latest'
    container_name: apache-network
    ports:
      - '8080:80'
    volumes:
      - ./app:/app
    labels:
      - traefik.http.routers.apache.rule=Host(`apache.localhost`)
      - traefik.http.routers.apache.tls=true
      - traefik.http.routers.apache.tls.certresolver=letsencrypt
      - traefik.http.services.apache.loadbalancer.server.port=80
    networks:
      - internal
      - web
    restart: unless-stopped

  apache1:
    image: 'bitnami/apache:latest'
    container_name: apache-network1
    ports:
      - '8081:80'
    volumes:
      - ./app:/app
    labels:
      - traefik.http.routers.apache1.rule=Host(`apache1.localhost`)
      - traefik.http.routers.apache1.tls=true
      - traefik.http.routers.apache1.tls.certresolver=letsencrypt
      - traefik.http.services.apache1.loadbalancer.server.port=80
    networks:
      - internal
      - web
    restart: unless-stopped

  dokuwiki:
    image: docker.io/bitnami/dokuwiki:20200729
    container_name: dokuwiki
    ports:
      - '8082:80'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
    labels:
      - traefik.http.routers.dokuwiki.rule=Host(`dokuwiki.localhost`)
      - traefik.http.routers.dokuwiki.tls=true
      - traefik.http.routers.dokuwiki.tls.certresolver=letsencrypt
      - traefik.http.services.dokuwiki.loadbalancer.server.port=80
    networks:
      - internal
      - web
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    labels:
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - internal
      - web
    environment: 
      - GF_SERVER_HTTP_PORT=3000
    restart: unless-stopped

  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    labels:
      - traefik.tcp.routers.mysql.rule=HostSNI(`mysql.localhost`)
      - traefik.tcp.routers.mysql.tls=true
      - traefik.tcp.routers.mysql.tls.certresolver=letsencrypt
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306
    networks:
      - internal
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8083:80'
    volumes:
      - ./nginx:/usr/share/nginx/html
    labels:
      - traefik.http.routers.nginx.rule=Host(`nginx.localhost`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=letsencrypt
      - traefik.http.services.nginx.loadbalancer.server.port=80
    networks:
      - internal
      - web
    restart: unless-stopped

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    ports:
      - '8080:80'  
      - '8443:443'
      - '2222:22' 
    restart: unless-stopped
    volumes:
      - './gitlab/config:/etc/gitlab'    
      - './gitlab/logs:/var/log/gitlab'     
      - './gitlab/data:/var/opt/gitlab'    
    networks:
      - internal
      - web


volumes:
  grafana_data:
  dokuwiki_data:
  mysql_data:

networks:
  web:
    external: true
  internal:
    external: false
